AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    upload

    Simple SAM package to upload an image to S3 bucket
    
Globals:
    Function:
        Timeout: 3

Resources:
    UploadFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: upload/build/
            Handler: app.upload
            Runtime: python3.6
            Environment:
                Variables:
                    PARAM1: VALUE
            Events:
                UploadImage:
                    Type: Api
                    Properties:
                        Path: /upload
                        Method: post

Outputs:
    UploadApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    UploadFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt UploadFunction.Arn

    UploadFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt HelloWorldFunctionRole.Arn
